apiVersion: apps/v1
kind: Deployment
metadata:
  name: helsesjekk-bot
  labels:
    app: helsesjekk-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helsesjekk-bot
  template:
    metadata:
      labels:
        app: helsesjekk-bot
    spec:
      containers:
        - name: helsesjekk-bot
          image: FULL_IMAGE_NAME
          envFrom:
            - secretRef:
                name: helsesjekk-bot
          resources:
            requests:
              memory: '512Mi'
              cpu: '128m'
            limits:
              memory: '512Mi'
              cpu: '256m'
